export enum Role {
  TRAINER = 'TRAINER',
  TRAINEE = 'TRAINEE',
}

export enum PersonaType {
  CANDIDATE = 'CANDIDATE',
  EMPLOYEE = 'EMPLOYEE',
  REFEREE = 'REFEREE',
  MANAGER = 'MANAGER',
  COLLEAGUE = 'COLLEAGUE',
}

export enum QualityTier {
  UNQUALIFIED = 'UNQUALIFIED',
  BORDERLINE = 'BORDERLINE',
  STRONG = 'STRONG',
}

export enum ProgressStatus {
  LOCKED = 'LOCKED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  GRADED = 'GRADED',
}

export enum InterviewType {
  SCOPING = 'SCOPING',
  SELECTION = 'SELECTION',
  REFERENCE = 'REFERENCE',
  PROBATION_CHECKIN = 'PROBATION_CHECKIN',
  APPRAISAL_360 = 'APPRAISAL_360',
  WELFARE = 'WELFARE',
  DISCIPLINARY = 'DISCIPLINARY',
  CAREER = 'CAREER',
  EXIT = 'EXIT',
}
